### ISSUE TITLE
Task list for tvOS support

### ISSUE THREAD

**Issue by kishikawakatsumi** [realm/realm-cocoa#2691]
### Documentation
- [x] Installation
- [x] Limitation
  - [x] Storage
  - [x] App size
  - [x] ~~Encryption~~
  - [x] Inter process notification
- [x] Use cases
  - [x] Bundled data
  - [x] Inteligent Cache

### Unit tests
- [x] Logic tests (on Simulator)
- [x] Tests on device

### Sample code
- [x] Bundled data
- [x] Cache

### Build/Release Automation
- [x] Core
- [x] Realm/RealmSwift
- [x] CocoaPods
- [x] Carthage

I'd like to get your feedback.
/cc @jpsim @mrackwitz @timanglade @bigfish24

**Comment by jpsim** [comment]
@bigfish24 was kind enough to lend his tv for our CI system until Realm can buy one when they go on sale on Monday. I've updated our CI setup to automatically attach the tv to a worker VM, which is tagged with `appletv` in Jenkins.

We now need to create a `build.sh` command similar to `test-ios-devices` that will pick up a TV if it's available and run the unit tests on that.

**Comment by kishikawakatsumi** [comment]
Unit testing on simulator available on https://github.com/realm/realm-cocoa/pull/2721

**Comment by kishikawakatsumi** [comment]
tvOS support has been released in 0.97
