### ISSUE TITLE
Update object server tests to work with ROS v2.0

### ISSUE THREAD

**Issue by bdash** [realm/realm-cocoa#5296]
ROS v2.0 has different packaging and command-line interface than ROS v1.0. We need to update our test harness to accommodate the differences in order to continue to test against current versions of sync.

Work that still remains to be done:
- [ ] Enable `testReadAccess` test. _Fixed by https://github.com/realm/ros/pull/475_
- [x] Enable `testWriteAccessViaUsername` test. ~_Fix forthcoming in next ROS per https://github.com/realm/ros/issues/426_~ Filed https://github.com/realm/ros/issues/508.
- [x] Enable `testDeletingPermission` test. This test passes in isolation but fails when run in the middle of the entire suite. It's possible that https://github.com/realm/ros/issues/437 is the cause.
- [ ] Enable `testDeleteRealmUponPermissionDenied` test. _Fixed by https://github.com/realm/ros/pull/475_ 
- [x] All other permissions tests need to be re-enabled and ported over.
- [x] Fix how admin users are created; re-enable tests that depend on admin users (`testRetrieveUserInfo`) - _#5341_
- [x] Fix and re-enable the password change tests (`testUserChangePassword`, `testOtherUserChangePassword`) -- _#5341_
- [x] Fix and re-enable the test that opens a Realm with the admin token (`testOpenRealmWithAdminToken`) -- _https://github.com/realm/realm-cocoa/pull/5332_
- [x] Fix and re-enable the test that logs in a user based on the admin token (`testAdminTokenAuthentication`) -- _https://github.com/realm/realm-cocoa/pull/5332_
- [x] Fix the sync error handler test (`testSyncErrorHandlerErrorDomain`) -- _#5333_

**Comment by austinzheng** [comment]
Work that needs to be done

- [ ] All permissions tests need to be re-enabled and ported over.
- [ ] Fix how admin users are created; re-enable tests that depend on admin users (`testRetrieveUserInfo`)
- [ ] Fix and re-enable the password change tests (`testUserChangePassword`, `testOtherUserChangePassword`)
- [ ] Fix and re-enable the test that opens a Realm with the admin token (`testOpenRealmWithAdminToken`)
- [ ] Fix and re-enable the test that logs in a user based on the admin token (`testAdminTokenAuthentication`)
- [ ] Fix the sync error handler test (`testSyncErrorHandlerErrorDomain`)

**Comment by bmunkholm** [comment]
@austinzheng Will you update status on this please with latest alpha.35?

**Comment by austinzheng** [comment]
A number of items were fixed by upgrading to alpha 35 and making corresponding changes; they are contained in [this PR](https://github.com/realm/realm-cocoa/pull/5328/). We put together this list after that PR was merged; I can add the items that PR fixed to the list if you'd like.

**Comment by austinzheng** [comment]
I have updated this issue with a fine-grained description of work remaining to be done. There are a number of issues other bindings have uncovered with ROS that our tests don't cover; it would be nice (but not mandatory) to write tests for those as well as they're fixed in time for the 3.0 release.

**Comment by austinzheng** [comment]
Updating Cocoa's ROS dependency to `rc-1` is blocked on https://github.com/realm/ros/issues/472.

**Comment by bmunkholm** [comment]
Looks like realm/ros#472 is not blocking anymore @austinzheng ?

**Comment by austinzheng** [comment]
It's not blocking, but now https://github.com/realm/ros/issues/438 is blocking it.
